/**
 * Portable data dump for the self-hosted (bundled Postgres) deploy — no pg_dump
 * needed. Reads the configured DATABASE_URL and writes db/data.sql: idempotent
 * INSERTs (ON CONFLICT DO NOTHING) for groups, members, messages, in FK order.
 *
 *   npx tsx --env-file=.env.local scripts/dump-data.ts
 *
 * Load it into the SumoPod Postgres (schema + seed-groups already applied by the
 * image's init hook on a fresh volume):
 *   docker compose exec -T db psql -U oshi -d oshi < db/data.sql
 *
 * app_state is intentionally skipped (OAuth tokens / Gmail watch cursor are
 * deployment-scoped cruft; the app recreates defaults).
 */
import "dotenv/config";
import { writeFileSync } from "node:fs";
import { Client } from "pg";
import { createSql, type Sql } from "../src/lib/server/sql";

// pg's escapeLiteral is a prototype method that needs no live connection.
const lit = (s: string) => new Client().escapeLiteral(s);

type Col =
  | { name: string; kind: "text" | "num" | "bool" }
  | { name: string; kind: "jsonb" }
  | { name: string; kind: "textarr" };

function value(v: unknown, kind: Col["kind"]): string {
  if (v === null || v === undefined) return "NULL";
  switch (kind) {
    case "num":
      return String(v);
    case "bool":
      return v ? "TRUE" : "FALSE";
    case "jsonb":
      return `${lit(JSON.stringify(v))}::jsonb`;
    case "textarr": {
      const arr = v as string[];
      return arr.length === 0 ? "ARRAY[]::text[]" : `ARRAY[${arr.map((e) => lit(e)).join(",")}]::text[]`;
    }
    case "text":
      return lit(String(v));
  }
}

async function dumpTable(sql: Sql, table: string, cols: Col[], keys: string[]): Promise<string> {
  const quoted = cols.map((c) => `"${c.name}"`).join(", ");
  // Re-load must repair drifted rows (e.g. blob URLs → /media/), so conflicting
  // rows are overwritten from the dump rather than skipped.
  const updatable = cols.filter((c) => !keys.includes(c.name));
  const setClause = updatable.map((c) => `"${c.name}" = excluded."${c.name}"`).join(", ");
  const conflict = updatable.length === 0
    ? `on conflict (${keys.join(", ")}) do nothing`
    : `on conflict (${keys.join(", ")}) do update set ${setClause}`;
  const rows = (await sql.query(`select ${quoted} from ${table}`)) as Array<Record<string, unknown>>;
  const lines = [`-- ${table}: ${rows.length} rows`];
  for (const row of rows) {
    const vals = cols.map((c) => value(row[c.name], c.kind)).join(", ");
    lines.push(`insert into ${table} (${quoted}) values (${vals}) ${conflict};`);
  }
  return lines.join("\n");
}

async function main(): Promise<void> {
  const sql = createSql();
  const groups = await dumpTable(sql, "groups", [
    { name: "name", kind: "text" },
    { name: "sort_order", kind: "num" },
  ], ["name"]);
  const members = await dumpTable(sql, "members", [
    { name: "id", kind: "text" },
    { name: "name", kind: "text" },
    { name: "group", kind: "text" },
    { name: "source", kind: "text" },
    { name: "unread", kind: "num" },
    { name: "time", kind: "text" },
    { name: "sort_order", kind: "num" },
    { name: "email_addresses", kind: "textarr" },
    { name: "attribution_keys", kind: "textarr" },
    { name: "avatar_url", kind: "text" },
    { name: "blog_url", kind: "text" },
  ], ["id"]);
  const messages = await dumpTable(sql, "messages", [
    { name: "id", kind: "text" },
    { name: "member_id", kind: "text" },
    { name: "jp", kind: "text" },
    { name: "romaji", kind: "text" },
    { name: "en", kind: "text" },
    { name: "words", kind: "jsonb" },
    { name: "time", kind: "text" },
    { name: "source", kind: "text" },
    { name: "image_url", kind: "text" },
    { name: "long", kind: "bool" },
    { name: "status", kind: "text" },
    { name: "error", kind: "text" },
    { name: "created_at", kind: "num" },
    { name: "gmail_message_id", kind: "text" },
    { name: "from_email", kind: "text" },
    { name: "from_name", kind: "text" },
    { name: "ingest_source", kind: "text" },
    { name: "external_id", kind: "text" },
    { name: "media_type", kind: "text" },
  ], ["id"]);

  const out = [
    "-- Oshi Inbox data dump (generated by scripts/dump-data.ts).",
    "-- Load: docker compose exec -T db psql -U oshi -d oshi < db/data.sql",
    "begin;",
    groups,
    members,
    messages,
    "commit;",
    "",
  ].join("\n\n");
  writeFileSync("db/data.sql", out, "utf8");
  console.log(`Wrote db/data.sql (${(Buffer.byteLength(out) / 1024 / 1024).toFixed(1)} MB)`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
